// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nadkzyzrbzooqeoiqlkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZGt6eXpyYnpvb3Flb2lxbGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzkyNzUsImV4cCI6MjA2MTE1NTI3NX0.-Fa7PESaHLLi99gGZJvfMZMIO9Jv8iiIVHYbA4aIqpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);